add music app

diff --git a/copy/opt/local/bin/install_nc_version b/copy/opt/local/bin/install_nc_version
--- a/copy/opt/local/bin/install_nc_version
+++ b/copy/opt/local/bin/install_nc_version
@@ -47,6 +47,7 @@ NEXTCLOUD_APPS="
   mail-v4.1.2.tar.gz
   maps-1.5.0.tar.gz
   memories.tar.gz
+  music.tar.gz
   news.tar.gz
   notes-v4.11.0.tar.gz
   oidc-1.3.0.tar.gz
@@ -68,9 +69,12 @@ for nc_app in ${NEXTCLOUD_APPS[@]}; do
   /opt/local/bin/curl -s -L -O "https://download.qutic.com/src/nextcloud/apps-$NEXTCLOUD_VERSION/${nc_app}"
   if [[ -f "${nc_app}" ]]; then
     echo "** Installing app: ${nc_app}"
-    /usr/bin/gtar xf "${nc_app}" && rm "${nc_app}" || true
+    /usr/bin/gtar xf "${nc_app}" || true
   fi
 done
+
+# cleanup archives
+rm *.tar.gz
 
 cd "${DESTDIR}"
 
